src/main/java/com/example/jsfdemo/domain/Person.java
package com.example.jsfdemo.domain;

import java.util.Date;

import javax.validation.constraints.Min;
import javax.validation.constraints.Past;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

public class Person {
	
	private String firstName = "";
	private String zipCode = "";
	private String pin = "";
	private Date dateOfBirth = new Date();
	private double weight;
	private boolean married;
	private int numOfChildren;
	
	@Size(min = 2, max = 20)
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	@Pattern(regexp = "[0-9]{2}-[0-9]{3}")
	public String getZipCode() {
		return zipCode;
	}
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}
	
	@Size(min = 2)
	public String getPin() {
		return pin;
	}
	public void setPin(String pin) {
		this.pin = pin;
	}
	
	@Min(0)
	public int getNumOfChildren() {
		return numOfChildren;
	}
	public void setNumOfChildren(int numOfChildren) {
		this.numOfChildren = numOfChildren;
	}
	
	@Past
	public Date getDateOfBirth() {
		return dateOfBirth;
	}
	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}
	
	public double getWeight() {
		return weight;
	}
	public void setWeight(double weight) {
		this.weight = weight;
	}
	
	public boolean isMarried() {
		return married;
	}
	public void setMarried(boolean married) {
		this.married = married;
	}
	
}

src/main/java/com/example/jsfdemo/web/PersonFormBean.java
package com.example.jsfdemo.web;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.component.UIForm;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.model.ListDataModel;
import javax.faces.validator.ValidatorException;
import javax.inject.Inject;
import javax.inject.Named;

import com.example.jsfdemo.domain.Person;
import com.example.jsfdemo.service.PersonManager;

@SessionScoped
@Named("personBean")
public class PersonFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Person person = new Person();

	private ListDataModel<Person> persons = new ListDataModel<Person>();

	@Inject
	private PersonManager pm;

	public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public ListDataModel<Person> getAllPersons() {
		persons.setWrappedData(pm.getAllPersons());
		return persons;
	}

	// Actions
	public String addPerson() {
		pm.addPerson(person);
		return "showPersons";
		//return null;
	}

	public String deletePerson() {
		Person personToDelete = persons.getRowData();
		pm.deletePerson(personToDelete);
		return null;
	}

	// Validators

	// Business logic validation
	public void uniquePin(FacesContext context, UIComponent component,
			Object value) {

		String pin = (String) value;

		for (Person person : pm.getAllPersons()) {
			if (person.getPin().equalsIgnoreCase(pin)) {
				FacesMessage message = new FacesMessage(
						"Person with this PIN already exists in database");
				message.setSeverity(FacesMessage.SEVERITY_ERROR);
				throw new ValidatorException(message);
			}
		}
	}

	// Multi field validation with <f:event>
	// Rule: first two digits of PIN must match last two digits of the year of
	// birth
	public void validatePinDob(ComponentSystemEvent event) {

		UIForm form = (UIForm) event.getComponent();
		UIInput pin = (UIInput) form.findComponent("pin");
		UIInput dob = (UIInput) form.findComponent("dob");

		if (pin.getValue() != null && dob.getValue() != null
				&& pin.getValue().toString().length() >= 2) {
			String twoDigitsOfPin = pin.getValue().toString().substring(0, 2);
			Calendar cal = Calendar.getInstance();
			cal.setTime(((Date) dob.getValue()));

			String lastDigitsOfDob = ((Integer) cal.get(Calendar.YEAR))
					.toString().substring(2);

			if (!twoDigitsOfPin.equals(lastDigitsOfDob)) {
				FacesContext context = FacesContext.getCurrentInstance();
				context.addMessage(form.getClientId(), new FacesMessage(
						"PIN doesn't match date of birth"));
				context.renderResponse();
			}
		}
	}
}

src/main/webapp/add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<h:form id="personform">
			<h:panelGrid columns="2">

				<h:outputText value="Add Person with very simple form" />
				<h:commandLink action="addSimple?faces-redirect=true">
					<h:outputText value=" Add person " />
				</h:commandLink>

				<h:outputText value="Add Person with some validators" />
				<h:commandLink action="addValidation?faces-redirect=true">
					<h:outputText value=" Add person " />
				</h:commandLink>

				<h:outputText value="Add Person with JSF 2.0 ajax support" />
				<h:commandLink action="addAjax?faces-redirect=true">
					<h:outputText value=" Add person " />
				</h:commandLink>

				<h:outputText value="Add Person with RichFaces support" />
				<h:commandLink action="addRF?faces-redirect=true">
					<h:outputText value=" Add person " />
				</h:commandLink>

			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/addAjax.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">

		<h:form id="personForm">
			<h:panelGrid columns="2">

				<h:outputText value="#{msg.personFirstNameLabel}" />
				<h:inputText id="firstName" value="#{personBean.person.firstName}"
					required="#{true}" />

				<h:outputText value="#{msg.personPinLabel}" />
				<h:inputText id="pin" value="#{personBean.person.pin}"
					validator="#{personBean.uniquePin}" required="#{true}">
					<f:validator validatorId="pinValidator" />
					<f:ajax execute="@this" render="messages beanState" />
				</h:inputText>

				<h:outputText value="#{msg.personDobLabel}" />
				<h:inputText id="dob" value="#{personBean.person.dateOfBirth}">
					<f:convertDateTime type="date" pattern="dd.MM.yyyy" />
				</h:inputText>

				<h:outputText value="#{msg.personZipCodeLabel}" />
				<h:inputText id="zipCode" value="#{personBean.person.zipCode}" />

				<h:outputText value="#{msg.personWeightLabel}" />
				<h:inputText id="weight" value="#{personBean.person.weight}">
					<f:validateDoubleRange minimum="20.5" maximum="150.5" />
					<f:ajax execute="@this" render="messages beanState" />
				</h:inputText>

				<h:outputText value="#{msg.personNumOfChildrenLabel}" />
				<h:inputText id="noc" value="#{personBean.person.numOfChildren}">

				</h:inputText>

			</h:panelGrid>

			<h:commandButton value="#{msg.personFormOKButton}"
				action="#{personBean.addPerson}" />


			<h:panelGrid>
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

			<h:panelGrid id="beanState" columns="2">
				<h:outputText value="#{msg.personFirstNameLabel}" />
				<h:outputText id="nameOutput" value="#{personBean.person.firstName}" />

				<h:outputText value="#{msg.personPinLabel}" />
				<h:outputText id="pinOutput" value="#{personBean.person.pin}" />

				<h:outputText value="#{msg.personDobLabel}" />
				<h:outputText id="dobOutput"
					value="#{personBean.person.dateOfBirth}" />
			</h:panelGrid>

		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/addRF.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<ui:define name="content">
		<h:form id="personForm">
			<h:panelGrid columns="2">
			
				<h:outputText value="#{msg.personFirstNameLabel}" />
				<h:inputText id="name" value="#{personBean.person.firstName}">
					<a4j:ajax render="messages" execute="@this" />
				</h:inputText>

				<h:outputText value="#{msg.personPinLabel}" />
				<h:inputText id="pin" value="#{personBean.person.pin}" />


				<h:outputText value="#{msg.personDobLabel}" />

				<rich:calendar value="#{personBean.person.dateOfBirth}"
					id="calendar" datePattern="dd.MM.yyyy" showApplyButton="#{true}"
					cellWidth="24px" cellHeight="22px" style="width:200px">
					<a4j:ajax render="messages" execute="@this" />
				</rich:calendar>
			</h:panelGrid>

			<h:panelGrid>
				<h:messages for="" />
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

			<a4j:outputPanel ajaxRendered="true">
				<h:panelGrid columns="2">

					<h:outputText value="#{msg.personFirstNameLabel}" />
					<h:outputText id="nameOutput"
						value="#{personBean.person.firstName}" />

					<h:outputText value="#{msg.personPinLabel}" />
					<h:outputText id="pinOutput" value="#{personBean.person.pin}" />


					<h:outputText value="#{msg.personDobLabel}" />
					<h:outputText id="dobOutput"
						value="#{personBean.person.dateOfBirth}" />

				</h:panelGrid>
			</a4j:outputPanel>
		</h:form>

	</ui:define>
</ui:composition>

src/main/webapp/addSimple.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:rich="http://richfaces.org/rich"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<h:form id="personform">
			<h:panelGrid columns="2">

				<h:outputText value="#{msg.personFirstNameLabel}" />
				<h:inputText id="name" value="#{personBean.person.firstName}" />

				<h:outputText value="#{msg.personPinLabel}" />
				<h:inputText id="yob" value="#{personBean.person.pin}" />
				
				<h:outputText value="#{msg.personDobLabel}" />		
				<rich:calendar value="#{personBean.person.dateOfBirth}"
					id="calendar" datePattern="dd.MM.yyyy" showApplyButton="#{true}"
					cellWidth="24px" cellHeight="22px" style="width:200px">
				</rich:calendar>
				
			</h:panelGrid>

			<h:commandButton value="#{msg.personFormOKButton}"
				action="#{personBean.addPerson}" styleClass="btn btn-primary"/>
				
			<h:panelGrid>
				<h:messages showDetail="#{true}" showSummary="#{false}" />
			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/addValidation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">

		<h:form id="personForm">
            <f:event type="postValidate" listener="#{personBean.validatePinDob}" />
            
			<h:panelGrid columns="2">

				<h:outputText value="#{msg.personFirstNameLabel}" />
				<h:inputText id="firstName" value="#{personBean.person.firstName}" required="#{true}"/>

				<h:outputText value="#{msg.personPinLabel}" />
				<h:inputText id="pin" value="#{personBean.person.pin}"
					validator="#{personBean.uniquePin}" required="#{true}">
					<f:validator validatorId="pinValidator" />
				</h:inputText>

				<h:outputText value="#{msg.personDobLabel}" />
				<h:inputText id="dob" value="#{personBean.person.dateOfBirth}">
				  <f:convertDateTime type="date" pattern="dd.MM.yyyy" />
				</h:inputText>

				<h:outputText value="#{msg.personZipCodeLabel}" />
				<h:inputText id="zipCode" value="#{personBean.person.zipCode}" />

				<h:outputText value="#{msg.personWeightLabel}" />
				<h:inputText id="weight" value="#{personBean.person.weight}">
					<f:validateDoubleRange minimum="20.5" maximum="150.5" />
				</h:inputText>
			</h:panelGrid>
			
			<h:commandButton value="#{msg.personFormOKButton}"
				action="#{personBean.addPerson}" />


			<h:panelGrid>
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>
		</h:form>

	</ui:define>
</ui:composition>

src/main/webapp/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<p>#{msg.applicationInfo}</p>
	</ui:define>
</ui:composition>

src/main/webapp/index.jsp
<% response.sendRedirect("home.jsf"); %>

src/main/webapp/showPersons.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	
	<ui:define name="content">
	
    <h:form>
    
     <h:dataTable value="#{personBean.allPersons}" var="item" styleClass="table table-hover">
      <f:facet name="header">#{msg.personAllLabel}</f:facet>
      
      <h:column>
        <f:facet name="header">#{msg.personFirstNameLabel}</f:facet>
        #{item.firstName}
      </h:column>
      
      <h:column>
        <f:facet name="header">#{msg.personPinLabel}</f:facet>
        #{item.pin}
      </h:column>
      
      <h:column>
        <f:facet name="header">#{msg.personDobLabel}</f:facet>
        #{item.dateOfBirth}
      </h:column>
      
      <h:column>
        <f:facet name="header">#{msg.action}</f:facet>
        <h:commandLink value="#{msg.actionDelete}" action="#{personBean.deletePerson}"/>
      </h:column>
      
     </h:dataTable>
    </h:form>
      
	</ui:define>
	
</ui:composition>

src/main/webapp/templates/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><ui:insert name="windowTitle">#{msg.mainWindowTitle}</ui:insert>
	</title>
</h:head>
<h:body>
  <h:outputStylesheet library="css" name="#{initParam['style']}" target="body" />
	<div class="heading well">
	  <ui:insert name="heading">
       #{msg.mainHeading}
      </ui:insert>
    </div>
	<div class="menuAndContent">
	 <div class="menu">
	   <ui:insert name="menu">
         <ui:include src="/views/main/menu.xhtml" />
       </ui:insert>
      </div>
	  <div class="content container">
	  	<div class="row-fluid">
	  		<div class="span12">
	     		<ui:insert name="content" />
     		</div>
     	</div>
       </div>
	</div>
</h:body>
</html>

src/main/webapp/views/main/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
  <div>
	<h:form>
	  	<ul class="nav nav-tabs">
			<li>
			  <h:commandLink action="home?faces-redirect=true">
				<h:outputText value="#{msg.linkHome}" />
			  </h:commandLink>
			</li>
			<li>
			  <h:commandLink action="addSimple?faces-redirect=true">
				<h:outputText value="#{msg.personAddLabel}" />
			  </h:commandLink></li>
			<li>
			  <h:commandLink action="showPersons?faces-redirect=true">
				 <h:outputText value="#{msg.personAllLabel}" />
			  </h:commandLink>
			</li>
		</ul>
   </h:form>
  </div>
</ui:composition>